/**
 * @file email-signature-generator.ts
 * @description Generates HTML email signatures with the brand logo and customizable fields
 */

import { SVGLogo } from '@/lib/types';
import { EmailSignatureTemplate, EmailSignatureType } from './mockup-types';
import { svgToDataUrl } from './mockup-generator';
import { ErrorCategory, handleError } from '@/lib/utils/error-handler';

/**
 * Generates an HTML email signature with embedded logo
 */
export function generateEmailSignature(
  logo: string | SVGLogo,
  templateId: string,
  userData: Record<string, string>,
  brandName: string = 'Brand Name',
  colorScheme: 'light' | 'dark' = 'light'
): string {
  try {
    // Extract SVG code if SVGLogo object is provided
    const svgCode = typeof logo === 'string' ? logo : logo.svgCode;
    
    // Get the template
    const template = EMAIL_SIGNATURE_TEMPLATES.find(t => t.id === templateId);
    if (!template) {
      throw new Error(`Email signature template with ID "${templateId}" not found`);
    }

    // Convert SVG to data URL for embedding in HTML
    const logoDataUrl = svgToDataUrl(svgCode);
    
    // Get colors based on scheme
    const colors = colorScheme === 'dark' ? template.darkColors : template.lightColors;
    
    // Replace template variables with actual values
    let html = template.html;
    
    // Replace logo placeholder
    html = html.replace(/\{LOGO_URL\}/g, logoDataUrl);
    
    // Replace color placeholders
    html = html.replace(/\{COLOR_PRIMARY\}/g, colors.primary);
    html = html.replace(/\{COLOR_SECONDARY\}/g, colors.secondary);
    html = html.replace(/\{COLOR_TEXT\}/g, colors.text);
    html = html.replace(/\{COLOR_BACKGROUND\}/g, colors.background);
    html = html.replace(/\{COLOR_ACCENT\}/g, colors.accent);
    
    // Replace brand name
    html = html.replace(/\{BRAND_NAME\}/g, brandName);
    
    // Replace user data fields
    Object.entries(userData).forEach(([key, value]) => {
      const regex = new RegExp(`\\{${key.toUpperCase()}\\}`, 'g');
      html = html.replace(regex, value);
    });
    
    // Replace any remaining placeholders with empty strings
    html = html.replace(/\{[A-Z_]+\}/g, '');
    
    return html;
  } catch (error) {
    handleError(error, {
      category: ErrorCategory.EXTERNAL,
      context: {
        templateId,
        operation: 'generateEmailSignature'
      },
      rethrow: true
    });
    return ''; // Unreachable due to rethrow, but TypeScript needs it
  }
}

/**
 * Generates a downloadable HTML file for an email signature
 */
export function generateEmailSignatureFile(
  logo: string | SVGLogo,
  templateId: string,
  userData: Record<string, string>,
  brandName: string = 'Brand Name',
  colorScheme: 'light' | 'dark' = 'light'
): { html: string, filename: string } {
  const signature = generateEmailSignature(logo, templateId, userData, brandName, colorScheme);
  const template = EMAIL_SIGNATURE_TEMPLATES.find(t => t.id === templateId);
  const filename = `${brandName.replace(/\s+/g, '-').toLowerCase()}-email-signature.html`;
  
  // Wrap in a complete HTML document for easy importing
  const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>${brandName} Email Signature</title>
  <style>
    body { font-family: Arial, sans-serif; padding: 20px; }
    .instructions { margin-bottom: 30px; }
    .signature-container { padding: 20px; border: 1px dashed #ccc; }
    code { background: #f5f5f5; padding: 2px 4px; border-radius: 3px; }
  </style>
</head>
<body>
  <div class="instructions">
    <h1>${brandName} Email Signature</h1>
    <p>Follow these steps to add this signature to your email client:</p>
    <h3>Gmail:</h3>
    <ol>
      <li>Go to Gmail Settings (gear icon &gt; See all settings)</li>
      <li>Under the "General" tab, scroll down to "Signature"</li>
      <li>Click "Create new" or select an existing signature to edit</li>
      <li>Select all content in the box below and copy (Ctrl+A, Ctrl+C)</li>
      <li>Paste into the signature editor in Gmail (Ctrl+V)</li>
      <li>Click "Save Changes" at the bottom of the page</li>
    </ol>
    <h3>Outlook:</h3>
    <ol>
      <li>Go to Outlook Settings &gt; View all Outlook settings</li>
      <li>Go to Mail &gt; Compose and reply</li>
      <li>Under "Email signature", select all content in the box below and copy</li>
      <li>Paste into the signature editor</li>
      <li>Click "Save"</li>
    </ol>
  </div>
  
  <h3>Your Signature:</h3>
  <div class="signature-container">
    ${signature}
  </div>
  
  <p><small>Generated by AI Logo Generator</small></p>
</body>
</html>`;

  return { html, filename };
}

/**
 * Downloads the email signature as an HTML file
 */
export function downloadEmailSignature(
  logo: string | SVGLogo,
  templateId: string,
  userData: Record<string, string>,
  brandName: string = 'Brand Name',
  colorScheme: 'light' | 'dark' = 'light'
): void {
  try {
    const { html, filename } = generateEmailSignatureFile(logo, templateId, userData, brandName, colorScheme);
    
    // Create a Blob and download link
    const blob = new Blob([html], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    
    // Clean up
    setTimeout(() => URL.revokeObjectURL(url), 100);
  } catch (error) {
    handleError(error, {
      category: ErrorCategory.UI,
      context: {
        operation: 'downloadEmailSignature',
        templateId
      }
    });
  }
}

/**
 * Default email signature templates
 */
export const EMAIL_SIGNATURE_TEMPLATES: EmailSignatureTemplate[] = [
  {
    id: 'minimalist',
    name: 'Minimalist',
    type: EmailSignatureType.MINIMALIST,
    description: 'Clean, modern signature with logo and essential info',
    lightColors: {
      primary: '#3B82F6',
      secondary: '#1E40AF',
      text: '#1F2937',
      background: '#FFFFFF',
      accent: '#DBEAFE'
    },
    darkColors: {
      primary: '#3B82F6',
      secondary: '#93C5FD',
      text: '#F3F4F6',
      background: '#1F2937',
      accent: '#1E40AF'
    },
    html: `
    <table cellpadding="0" cellspacing="0" style="font-family: Arial, sans-serif; color: {COLOR_TEXT}; max-width: 500px; border-collapse: collapse;">
      <tr>
        <td style="vertical-align: top; padding-right: 15px; width: 100px;">
          <img src="{LOGO_URL}" alt="{BRAND_NAME}" style="width: 100px; max-width: 100%;">
        </td>
        <td style="vertical-align: top; padding-left: 15px; border-left: 2px solid {COLOR_PRIMARY};">
          <div style="font-weight: bold; font-size: 16px; color: {COLOR_PRIMARY};">{NAME}</div>
          <div style="font-size: 14px; margin-bottom: 5px;">{TITLE}</div>
          <div style="font-size: 13px; margin-bottom: 5px;">{BRAND_NAME}</div>
          <div style="font-size: 12px; margin-bottom: 2px;"><a href="mailto:{EMAIL}" style="color: {COLOR_SECONDARY}; text-decoration: none;">{EMAIL}</a></div>
          <div style="font-size: 12px; margin-bottom: 2px;"><a href="tel:{PHONE}" style="color: {COLOR_SECONDARY}; text-decoration: none;">{PHONE}</a></div>
          <div style="font-size: 12px;"><a href="{WEBSITE}" style="color: {COLOR_SECONDARY}; text-decoration: none;">{WEBSITE}</a></div>
        </td>
      </tr>
    </table>
    `
  },
  {
    id: 'professional',
    name: 'Professional',
    type: EmailSignatureType.PROFESSIONAL,
    description: 'Formal signature with clear hierarchy and contact details',
    lightColors: {
      primary: '#0F172A',
      secondary: '#334155',
      text: '#1F2937',
      background: '#FFFFFF',
      accent: '#E2E8F0'
    },
    darkColors: {
      primary: '#E2E8F0',
      secondary: '#94A3B8',
      text: '#F3F4F6',
      background: '#1F2937',
      accent: '#334155'
    },
    html: `
    <table cellpadding="0" cellspacing="0" style="font-family: Arial, sans-serif; color: {COLOR_TEXT}; max-width: 550px; border-collapse: collapse; border-bottom: 1px solid {COLOR_ACCENT}; padding-bottom: 15px;">
      <tr>
        <td style="vertical-align: middle; padding-right: 20px;">
          <img src="{LOGO_URL}" alt="{BRAND_NAME}" style="width: 120px; max-width: 100%;">
        </td>
        <td style="vertical-align: middle;">
          <div style="font-weight: bold; font-size: 18px; color: {COLOR_PRIMARY}; margin-bottom: 5px;">{NAME}</div>
          <div style="font-size: 14px; margin-bottom: 10px; color: {COLOR_SECONDARY};">{TITLE} | {BRAND_NAME}</div>
          <table cellpadding="0" cellspacing="0" style="font-size: 13px;">
            <tr>
              <td style="padding-right: 15px; padding-bottom: 3px;"><strong>Email:</strong></td>
              <td style="padding-bottom: 3px;"><a href="mailto:{EMAIL}" style="color: {COLOR_SECONDARY}; text-decoration: none;">{EMAIL}</a></td>
            </tr>
            <tr>
              <td style="padding-right: 15px; padding-bottom: 3px;"><strong>Phone:</strong></td>
              <td style="padding-bottom: 3px;"><a href="tel:{PHONE}" style="color: {COLOR_SECONDARY}; text-decoration: none;">{PHONE}</a></td>
            </tr>
            <tr>
              <td style="padding-right: 15px; padding-bottom: 3px;"><strong>Website:</strong></td>
              <td style="padding-bottom: 3px;"><a href="{WEBSITE}" style="color: {COLOR_SECONDARY}; text-decoration: none;">{WEBSITE}</a></td>
            </tr>
            <tr>
              <td style="padding-right: 15px;"><strong>Address:</strong></td>
              <td>{ADDRESS}</td>
            </tr>
          </table>
        </td>
      </tr>
    </table>
    `
  },
  {
    id: 'creative',
    name: 'Creative',
    type: EmailSignatureType.CREATIVE,
    description: 'Bold, eye-catching signature with social media links',
    lightColors: {
      primary: '#8B5CF6',
      secondary: '#6D28D9',
      text: '#1F2937',
      background: '#FFFFFF',
      accent: '#EDE9FE'
    },
    darkColors: {
      primary: '#A78BFA',
      secondary: '#C4B5FD',
      text: '#F3F4F6',
      background: '#1F2937',
      accent: '#6D28D9'
    },
    html: `
    <table cellpadding="0" cellspacing="0" style="font-family: Arial, sans-serif; color: {COLOR_TEXT}; max-width: 550px; border-collapse: collapse; background-color: {COLOR_BACKGROUND}; border-radius: 8px; overflow: hidden;">
      <tr>
        <td style="vertical-align: top; background-color: {COLOR_ACCENT}; padding: 15px; text-align: center; width: 150px;">
          <img src="{LOGO_URL}" alt="{BRAND_NAME}" style="width: 120px; max-width: 100%; margin-bottom: 10px;">
          <div style="font-weight: bold; font-size: 16px; color: {COLOR_PRIMARY}; margin-bottom: 5px;">{NAME}</div>
          <div style="font-size: 13px; margin-bottom: 10px; color: {COLOR_SECONDARY};">{TITLE}</div>
        </td>
        <td style="vertical-align: top; padding: 15px;">
          <div style="font-weight: bold; font-size: 16px; color: {COLOR_PRIMARY}; margin-bottom: 10px;">{BRAND_NAME}</div>
          <div style="font-size: 13px; margin-bottom: 5px;"><strong>Email:</strong> <a href="mailto:{EMAIL}" style="color: {COLOR_SECONDARY}; text-decoration: none;">{EMAIL}</a></div>
          <div style="font-size: 13px; margin-bottom: 5px;"><strong>Phone:</strong> <a href="tel:{PHONE}" style="color: {COLOR_SECONDARY}; text-decoration: none;">{PHONE}</a></div>
          <div style="font-size: 13px; margin-bottom: 10px;"><strong>Web:</strong> <a href="{WEBSITE}" style="color: {COLOR_SECONDARY}; text-decoration: none;">{WEBSITE}</a></div>
          
          <!-- Social media icons -->
          <div style="margin-top: 10px;">
            {LINKEDIN_URL ? '<a href="' + LINKEDIN_URL + '" style="display: inline-block; margin-right: 8px;"><img src="https://cdn2.iconfinder.com/data/icons/social-media-2285/512/1_Linkedin_unofficial_colored_svg-128.png" width="24" height="24" alt="LinkedIn" style="border: none;"></a>' : ''}
            {TWITTER_URL ? '<a href="' + TWITTER_URL + '" style="display: inline-block; margin-right: 8px;"><img src="https://cdn2.iconfinder.com/data/icons/social-media-2285/512/1_Twitter_colored_svg-128.png" width="24" height="24" alt="Twitter" style="border: none;"></a>' : ''}
            {INSTAGRAM_URL ? '<a href="' + INSTAGRAM_URL + '" style="display: inline-block; margin-right: 8px;"><img src="https://cdn2.iconfinder.com/data/icons/social-media-2285/512/1_Instagram_colored_svg-128.png" width="24" height="24" alt="Instagram" style="border: none;"></a>' : ''}
            {FACEBOOK_URL ? '<a href="' + FACEBOOK_URL + '" style="display: inline-block;"><img src="https://cdn2.iconfinder.com/data/icons/social-media-2285/512/1_Facebook_colored_svg-128.png" width="24" height="24" alt="Facebook" style="border: none;"></a>' : ''}
          </div>
        </td>
      </tr>
    </table>
    `
  },
  {
    id: 'compact',
    name: 'Compact',
    type: EmailSignatureType.COMPACT,
    description: 'Space-efficient signature with all essential information',
    lightColors: {
      primary: '#10B981',
      secondary: '#059669',
      text: '#1F2937',
      background: '#FFFFFF',
      accent: '#D1FAE5'
    },
    darkColors: {
      primary: '#34D399',
      secondary: '#6EE7B7',
      text: '#F3F4F6',
      background: '#1F2937',
      accent: '#059669'
    },
    html: `
    <table cellpadding="0" cellspacing="0" style="font-family: Arial, sans-serif; color: {COLOR_TEXT}; max-width: 400px; border-collapse: collapse;">
      <tr>
        <td style="vertical-align: middle; padding-right: 10px; width: 50px;">
          <img src="{LOGO_URL}" alt="{BRAND_NAME}" style="width: 50px; max-width: 100%;">
        </td>
        <td style="vertical-align: middle;">
          <div style="font-weight: bold; font-size: 14px; color: {COLOR_PRIMARY};">{NAME} | {TITLE}</div>
          <div style="font-size: 12px; margin-bottom: 3px;">{BRAND_NAME}</div>
          <div style="font-size: 11px;">
            <a href="mailto:{EMAIL}" style="color: {COLOR_SECONDARY}; text-decoration: none;">{EMAIL}</a> | 
            <a href="tel:{PHONE}" style="color: {COLOR_SECONDARY}; text-decoration: none;">{PHONE}</a> | 
            <a href="{WEBSITE}" style="color: {COLOR_SECONDARY}; text-decoration: none;">{WEBSITE}</a>
          </div>
        </td>
      </tr>
    </table>
    `
  }
];

/**
 * Get a template by ID
 */
export function getEmailTemplateById(id: string): EmailSignatureTemplate | undefined {
  return EMAIL_SIGNATURE_TEMPLATES.find(template => template.id === id);
}